export interface MockQuestion {
  id: string
  questionType: 'MCQ' | 'CODING' | 'DEBUGGING' | 'SQL'
  questionData: any
  difficulty: 'EASY' | 'MEDIUM' | 'HARD'
  topic: string
  marks: number
  orderIndex: number
  companyTags?: string[]
}

export interface MockAssessment {
  id: string
  title: string
  description: string
  type: string
  duration: number
  totalQuestions: number
  totalMarks: number
  passingMarks: number
  questions: MockQuestion[]
  negativeMarking: number
  questionPoolSize: number
  randomizeOnRetake: boolean
  companyPattern?: string
}

function mcq(
  id: string, text: string, options: { label: string; value: string }[],
  correctAnswer: string, explanation: string, difficulty: MockQuestion['difficulty'],
  topic: string, marks = 1, companyTags?: string[]
): MockQuestion {
  return { id, questionType: 'MCQ', difficulty, topic, marks, orderIndex: 0, companyTags, questionData: { text, options, correctAnswer, explanation } }
}

function coding(
  id: string, title: string, description: string, constraints: string,
  sampleInput: string, sampleOutput: string,
  testCases: { input: string; expectedOutput: string }[],
  hiddenTestCases: { input: string; expectedOutput: string }[],
  starterCode: Record<string, string>,
  difficulty: MockQuestion['difficulty'], topic: string, marks: number,
  explanation?: string, companyTags?: string[]
): MockQuestion {
  return { id, questionType: 'CODING', difficulty, topic, marks, orderIndex: 0, companyTags, questionData: { title, description, constraints, sampleInput, sampleOutput, testCases, hiddenTestCases, starterCode, explanation } }
}

const PY = 'def solution():\n    # Write your code here\n    pass\n'
const JS = 'function solution() {\n    // Write your code here\n    return null;\n}\n'
const JAVA = 'public class Main {\n    public static void main(String[] args) {\n        // Write your code here\n    }\n}'
const CPP = '#include <iostream>\nusing namespace std;\n\nint main() {\n    // Write your code here\n    return 0;\n}'
const STARTER = { python: PY, javascript: JS, java: JAVA, cpp: CPP }

// ═══════════════════════════════════════════════════════════════
// APTITUDE QUESTION POOL (55 questions)
// ═══════════════════════════════════════════════════════════════
const APTITUDE_POOL: MockQuestion[] = [
  // --- Quantitative (20) ---
  mcq('apt-q1', 'If a train 280 m long runs at 60 km/h, how much time to pass a platform 220 m long?',
    [{ label: 'A', value: '25 sec' }, { label: 'B', value: '30 sec' }, { label: 'C', value: '35 sec' }, { label: 'D', value: '40 sec' }],
    'B', 'Total distance = 280+220 = 500m. Speed = 60×5/18 = 50/3 m/s. Time = 500×3/50 = 30 sec.', 'EASY', 'Quantitative', 1),
  mcq('apt-q2', 'A man spends 60% of income and saves the rest. Income increases by 20%, spending by 10%. % change in savings?',
    [{ label: 'A', value: '25% increase' }, { label: 'B', value: '30% increase' }, { label: 'C', value: '35% increase' }, { label: 'D', value: '40% increase' }],
    'C', 'Let income=100. Spend=60, Save=40. New income=120, New spend=66, New save=54. Increase = 14/40×100 = 35%.', 'MEDIUM', 'Quantitative', 2),
  mcq('apt-q3', 'A shopkeeper gives 20% discount and still makes 20% profit. CP is ₹500. What is marked price?',
    [{ label: 'A', value: '₹700' }, { label: 'B', value: '₹720' }, { label: 'C', value: '₹750' }, { label: 'D', value: '₹800' }],
    'C', 'SP = 500×1.2 = 600. Marked×0.8 = 600, so Marked = 600/0.8 = ₹750.', 'EASY', 'Quantitative', 1),
  mcq('apt-q4', 'A and B do work in 12 days. B and C in 15 days. C and A in 20 days. How long will A alone take?',
    [{ label: 'A', value: '25 days' }, { label: 'B', value: '30 days' }, { label: 'C', value: '35 days' }, { label: 'D', value: '40 days' }],
    'B', '2(A+B+C) = 1/12+1/15+1/20 = 12/60 = 1/5. A+B+C = 1/10. A alone = 1/10-1/15 = 1/30 → 30 days.', 'MEDIUM', 'Quantitative', 2),
  mcq('apt-q5', 'Bag has 4 red, 5 blue, 6 green balls. Two drawn at random. Probability both green?',
    [{ label: 'A', value: '15/105' }, { label: 'B', value: '15/91' }, { label: 'C', value: '6/15' }, { label: 'D', value: '12/91' }],
    'B', 'Total=15. P(both green) = C(6,2)/C(15,2) = 15/105 = 15/91.', 'MEDIUM', 'Quantitative', 2),
  mcq('apt-q6', 'What is simple interest on ₹4000 at 8% p.a. for 3 years?',
    [{ label: 'A', value: '₹840' }, { label: 'B', value: '₹960' }, { label: 'C', value: '₹1020' }, { label: 'D', value: '₹1100' }],
    'B', 'SI = P×R×T/100 = 4000×8×3/100 = ₹960.', 'EASY', 'Quantitative', 1),
  mcq('apt-q7', 'Average of 8 numbers is 15. One number 20 is replaced by 32. New average?',
    [{ label: 'A', value: '16.5' }, { label: 'B', value: '17' }, { label: 'C', value: '16' }, { label: 'D', value: '17.5' }],
    'A', 'Sum = 8×15 = 120. New sum = 120-20+32 = 132. New avg = 132/8 = 16.5.', 'MEDIUM', 'Quantitative', 2),
  mcq('apt-q8', 'A invests ₹6000 for 8 months, B ₹8000 for 6 months, C ₹10000 for 4 months. Profit ₹5000. B\'s share?',
    [{ label: 'A', value: '₹1600' }, { label: 'B', value: '₹1800' }, { label: 'C', value: '₹2000' }, { label: 'D', value: '₹1500' }],
    'A', 'Ratio = 48:48:40 = 6:6:5. B\'s share = 6/17×5000 ≈ ₹1764. Nearest option ₹1600.', 'HARD', 'Quantitative', 3),
  mcq('apt-q9', 'Cylinder r=7cm, h=14cm melted into spheres r=2cm. How many spheres?',
    [{ label: 'A', value: '32' }, { label: 'B', value: '38' }, { label: 'C', value: '42' }, { label: 'D', value: '48' }],
    'A', 'Vol cylinder = π×49×14 = 686π. Vol sphere = 4/3×π×8 = 32π/3. Number = 686π×3/32π = 64.3 ≈ 32.', 'HARD', 'Quantitative', 3),
  mcq('apt-q10', '15% of a number is 45. What is 40% of that number?',
    [{ label: 'A', value: '100' }, { label: 'B', value: '120' }, { label: 'C', value: '140' }, { label: 'D', value: '160' }],
    'B', '0.15x=45, x=300. 40% of 300 = 120.', 'EASY', 'Quantitative', 1),
  mcq('apt-q11', 'A boat goes 24km upstream and 24km downstream in 14 hours. Stream speed 2 km/h. Boat speed?',
    [{ label: 'A', value: '4 km/h' }, { label: 'B', value: '5 km/h' }, { label: 'C', value: '6 km/h' }, { label: 'D', value: '7 km/h' }],
    'B', '24/(x-2) + 24/(x+2) = 14. Solving gives x = 5 km/h.', 'MEDIUM', 'Quantitative', 2),
  mcq('apt-q12', 'If log₂(3x-5) = 4, find x.',
    [{ label: 'A', value: '5' }, { label: 'B', value: '7' }, { label: 'C', value: '9' }, { label: 'D', value: '11' }],
    'B', '3x-5 = 2⁴ = 16. 3x = 21. x = 7.', 'MEDIUM', 'Quantitative', 2),
  mcq('apt-q13', 'A sum amounts to ₹24200 in 2 years at CI 10% p.a. compounded annually. Principal?',
    [{ label: 'A', value: '₹18000' }, { label: 'B', value: '₹20000' }, { label: 'C', value: '₹22000' }, { label: 'D', value: '₹24000' }],
    'B', 'A = P(1.1)² = P×1.21. 24200 = P×1.21. P = ₹20000.', 'HARD', 'Quantitative', 3),
  mcq('apt-q14', 'LCM of 12, 18, and 24?',
    [{ label: 'A', value: '48' }, { label: 'B', value: '60' }, { label: 'C', value: '72' }, { label: 'D', value: '96' }],
    'C', '12=2²×3, 18=2×3², 24=2³×3. LCM = 2³×3² = 72.', 'EASY', 'Quantitative', 1),
  mcq('apt-q15', 'x+y=12, xy=32. Find x²+y².',
    [{ label: 'A', value: '80' }, { label: 'B', value: '90' }, { label: 'C', value: '100' }, { label: 'D', value: '110' }],
    'A', 'x²+y² = (x+y)²-2xy = 144-64 = 80.', 'EASY', 'Quantitative', 1),
  mcq('apt-q16', 'Milk and water in ratio 5:3. Add 4L water, ratio becomes 5:4. Original milk?',
    [{ label: 'A', value: '15 L' }, { label: 'B', value: '20 L' }, { label: 'C', value: '25 L' }, { label: 'D', value: '30 L' }],
    'B', '5x/(3x+4) = 5/4. 20x = 15x+20. 5x=20, x=4. Milk = 5×4 = 20L.', 'HARD', 'Quantitative', 3),
  mcq('apt-q17', 'Pipe fills tank in 8 hours. Leak takes 12 hours. Leak alone to empty?',
    [{ label: 'A', value: '20 hours' }, { label: 'B', value: '24 hours' }, { label: 'C', value: '28 hours' }, { label: 'D', value: '30 hours' }],
    'B', 'Net = 1/8-1/12 = 1/24. Leak alone = 24 hours.', 'MEDIUM', 'Quantitative', 2),
  mcq('apt-q18', 'A car travels 180 km in 3 hours. Speed in m/s?',
    [{ label: 'A', value: '50/3 m/s' }, { label: 'B', value: '50 m/s' }, { label: 'C', value: '60 m/s' }, { label: 'D', value: '20 m/s' }],
    'A', '60 km/h = 60×5/18 = 50/3 m/s.', 'EASY', 'Quantitative', 1),
  mcq('apt-q19', 'A man can row 5 km/h in still water. River flows at 2 km/h. 1 hour more upstream than downstream. Distance?',
    [{ label: 'A', value: '5.25 km' }, { label: 'B', value: '6.25 km' }, { label: 'C', value: '7.25 km' }, { label: 'D', value: '8.25 km' }],
    'A', 'd/3 - d/7 = 1. 4d/21 = 1. d = 5.25 km.', 'MEDIUM', 'Quantitative', 2),
  mcq('apt-q20', 'If 8 workers build a wall in 15 days, how many for 10 days?',
    [{ label: 'A', value: '10' }, { label: 'B', value: '12' }, { label: 'C', value: '14' }, { label: 'D', value: '16' }],
    'B', 'M1D1=M2D2. 8×15=M2×10. M2=12.', 'EASY', 'Quantitative', 1),

  // --- Logical Reasoning (18) ---
  mcq('apt-l1', 'Find next: 2, 6, 12, 20, 30, ?',
    [{ label: 'A', value: '40' }, { label: 'B', value: '42' }, { label: 'C', value: '44' }, { label: 'D', value: '36' }],
    'B', 'Pattern: 1×2=2, 2×3=6, 3×4=12, 4×5=20, 5×6=30, 6×7=42.', 'EASY', 'Logical Reasoning', 1),
  mcq('apt-l2', 'PLACE is coded as QMBDF. How is HOUSE coded?',
    [{ label: 'A', value: 'IPVTF' }, { label: 'B', value: 'IPUTF' }, { label: 'C', value: 'IPVTE' }, { label: 'D', value: 'IQVTF' }],
    'A', 'Each letter +1. H→I, O→P, U→V, S→T, E→F → IPVTF.', 'MEDIUM', 'Logical Reasoning', 2),
  mcq('apt-l3', 'Seven people in circle. P sits 3rd left of U. R sits 2nd right of Q. V between P and S. T not adjacent to S. Who opposite Q?',
    [{ label: 'A', value: 'P' }, { label: 'B', value: 'T' }, { label: 'C', value: 'U' }, { label: 'D', value: 'V' }],
    'C', 'Arranging: T,S,V,P,U,Q,R clockwise. Q opposite U.', 'HARD', 'Logical Reasoning', 3),
  mcq('apt-l4', 'FISH is coded as EHRG. How is BIRD coded?',
    [{ label: 'A', value: 'AHQC' }, { label: 'B', value: 'CJSE' }, { label: 'C', value: 'AHRC' }, { label: 'D', value: 'CHSE' }],
    'A', 'Each letter -1. B→A, I→H, R→Q, D→C → AHQC.', 'MEDIUM', 'Logical Reasoning', 2),
  mcq('apt-l5', 'Find odd one: 2, 4, 8, 16, 24, 32',
    [{ label: 'A', value: '4' }, { label: 'B', value: '24' }, { label: 'C', value: '16' }, { label: 'D', value: '32' }],
    'B', 'All except 24 are powers of 2.', 'EASY', 'Logical Reasoning', 1),
  mcq('apt-l6', 'A×B means A is father of B, A-B means A is sister of B, A+B means A is mother of B. How is P related to R in P×Q+R-S?',
    [{ label: 'A', value: 'Grandfather' }, { label: 'B', value: 'Father' }, { label: 'C', value: 'Uncle' }, { label: 'D', value: 'Grandmother' }],
    'A', 'P×Q = P father of Q. Q+R = Q mother of R. P is grandfather of R.', 'MEDIUM', 'Logical Reasoning', 2),
  mcq('apt-l7', 'Row of 40 students. Ravi 15th from left, Sita 12th from right. How many between?',
    [{ label: 'A', value: '13' }, { label: 'B', value: '14' }, { label: 'C', value: '15' }, { label: 'D', value: '12' }],
    'A', 'Ravi from right = 40-15+1=26. Between = 26-12-1=13.', 'EASY', 'Logical Reasoning', 1),
  mcq('apt-l8', 'Five friends A,B,C,D,E. A taller than B but shorter than C. D shorter than E but taller than A. Second tallest?',
    [{ label: 'A', value: 'A' }, { label: 'B', value: 'C' }, { label: 'C', value: 'D' }, { label: 'D', value: 'E' }],
    'D', 'C>E>D>A>B or C>E>A>D>B. E is second tallest.', 'HARD', 'Logical Reasoning', 3),
  mcq('apt-l9', 'Statement: All flowers are trees. Some trees are fruits. No fruit is vegetable. Conclusion I: Some vegetables are flowers. II: No vegetable is flower.',
    [{ label: 'A', value: 'Only I follows' }, { label: 'B', value: 'Only II follows' }, { label: 'C', value: 'Both follow' }, { label: 'D', value: 'Neither follows' }],
    'B', 'Since no fruit is vegetable and trees include fruits, flowers being trees cannot be vegetables. II follows.', 'HARD', 'Logical Reasoning', 3),
  mcq('apt-l10', 'CONTENT is coded as DPOUFO. How is PAPER coded?',
    [{ label: 'A', value: 'QBQFS' }, { label: 'B', value: 'QBPFS' }, { label: 'C', value: 'PBQFS' }, { label: 'D', value: 'QBRFS' }],
    'A', 'Each letter +1. P→Q, A→B, P→Q, E→F, R→S → QBQFS.', 'MEDIUM', 'Logical Reasoning', 2),
  mcq('apt-l11', 'Which number replaces? 3, 7, 15, ?, 63, 127',
    [{ label: 'A', value: '27' }, { label: 'B', value: '31' }, { label: 'C', value: '33' }, { label: 'D', value: '35' }],
    'B', 'Pattern: ×2+1. 15×2+1=31.', 'EASY', 'Logical Reasoning', 1),
  mcq('apt-l12', 'If today is Thursday, what day after 72 days?',
    [{ label: 'A', value: 'Saturday' }, { label: 'B', value: 'Sunday' }, { label: 'C', value: 'Monday' }, { label: 'D', value: 'Friday' }],
    'A', '72 mod 7 = 2. Thursday+2 = Saturday.', 'EASY', 'Logical Reasoning', 1),
  mcq('apt-l13', '6 persons in circle. A between F and B. C between E and D. Who opposite A?',
    [{ label: 'A', value: 'B' }, { label: 'B', value: 'C' }, { label: 'C', value: 'D' }, { label: 'D', value: 'E' }],
    'B', 'F-A-B and E-C-D alternate. C opposite A.', 'HARD', 'Logical Reasoning', 3),
  mcq('apt-l14', 'Man walks 5km east, turns right 3km, turns right 5km. Distance from start?',
    [{ label: 'A', value: '5 km' }, { label: 'B', value: '3 km' }, { label: 'C', value: '8 km' }, { label: 'D', value: '2 km' }],
    'B', 'East-west cancels (5 east, 5 west). Ends 3km south of start.', 'MEDIUM', 'Logical Reasoning', 2),
  mcq('apt-l15', 'All pens are books. All books are tables. Which is true?',
    [{ label: 'A', value: 'All tables are pens' }, { label: 'B', value: 'All pens are tables' }, { label: 'C', value: 'Some tables are not books' }, { label: 'D', value: 'No pens are tables' }],
    'B', 'By transitivity: all pens are tables.', 'EASY', 'Logical Reasoning', 1),
  mcq('apt-l16', 'Complete: Book : Reading as Fork : ?',
    [{ label: 'A', value: 'Eating' }, { label: 'B', value: 'Cooking' }, { label: 'C', value: 'Knife' }, { label: 'D', value: 'Food' }],
    'A', 'Book is used for reading, Fork is used for eating.', 'EASY', 'Logical Reasoning', 1),
  mcq('apt-l17', 'Statement: All engineers are smart. Some smart people are rich. Conclusion I: Some engineers are rich. II: Some rich people are smart.',
    [{ label: 'A', value: 'Only I follows' }, { label: 'B', value: 'Only II follows' }, { label: 'C', value: 'Both follow' }, { label: 'D', value: 'Neither follows' }],
    'B', 'I does not follow (no direct link). II follows (some smart are rich = some rich are smart).', 'MEDIUM', 'Logical Reasoning', 2),
  mcq('apt-l18', 'Fibonacci: 1, 1, 2, 3, 5, 8, ?',
    [{ label: 'A', value: '10' }, { label: 'B', value: '11' }, { label: 'C', value: '12' }, { label: 'D', value: '13' }],
    'D', 'Each = sum of previous two. 5+8=13.', 'EASY', 'Logical Reasoning', 1),

  // --- Verbal Ability (12) ---
  mcq('apt-v1', 'Choose synonym of "Ubiquitous":',
    [{ label: 'A', value: 'Rare' }, { label: 'B', value: 'Omnipresent' }, { label: 'C', value: 'Unique' }, { label: 'D', value: 'Scarce' }],
    'B', 'Ubiquitous means present everywhere, synonymous with omnipresent.', 'EASY', 'Verbal Ability', 1),
  mcq('apt-v2', 'Correct spelling:',
    [{ label: 'A', value: 'Accomodation' }, { label: 'B', value: 'Acommodation' }, { label: 'C', value: 'Accommodation' }, { label: 'D', value: 'Acomodation' }],
    'C', 'Accommodation has two c\'s and two m\'s.', 'EASY', 'Verbal Ability', 1),
  mcq('apt-v3', 'Error: "Neither the manager nor the employees was aware of the policy change."',
    [{ label: 'A', value: 'Neither the manager' }, { label: 'B', value: 'nor the employees' }, { label: 'C', value: 'was aware' }, { label: 'D', value: 'No error' }],
    'C', 'With "neither...nor", verb agrees with nearest subject. Should be "were aware".', 'MEDIUM', 'Verbal Ability', 2),
  mcq('apt-v4', 'Antonym of "Ephemeral":',
    [{ label: 'A', value: 'Temporary' }, { label: 'B', value: 'Permanent' }, { label: 'C', value: 'Short-lived' }, { label: 'D', value: 'Fleeting' }],
    'B', 'Ephemeral means short-lived. Opposite is permanent.', 'EASY', 'Verbal Ability', 1),
  mcq('apt-v5', 'Select correct passive: "The teacher was explaining the lesson."',
    [{ label: 'A', value: 'The lesson was explained by the teacher.' }, { label: 'B', value: 'The lesson was being explained by the teacher.' }, { label: 'C', value: 'The lesson is being explained by the teacher.' }, { label: 'D', value: 'The lesson had been explained by the teacher.' }],
    'B', 'Past continuous active → past continuous passive. Was explaining → was being explained.', 'MEDIUM', 'Verbal Ability', 2),
  mcq('apt-v6', 'Complete: "No sooner did he arrive ___ the meeting started."',
    [{ label: 'A', value: 'then' }, { label: 'B', value: 'than' }, { label: 'C', value: 'when' }, { label: 'D', value: 'and' }],
    'B', 'Correct phrase: "No sooner...than".', 'EASY', 'Verbal Ability', 1),
  mcq('apt-v7', 'Rearrange: "to / the / success / key / is / perseverance / achieving"',
    [{ label: 'A', value: 'Perseverance is the key to achieving success.' }, { label: 'B', value: 'Achieving success perseverance is the key to.' }, { label: 'C', value: 'The key to achieving success is perseverance.' }, { label: 'D', value: 'Success is the key to achieving perseverance.' }],
    'C', 'Correct: "The key to achieving success is perseverance."', 'MEDIUM', 'Verbal Ability', 2),
  mcq('apt-v8', 'Choose synonym of "Prolific":',
    [{ label: 'A', value: 'Productive' }, { label: 'B', value: 'Lazy' }, { label: 'C', value: 'Rare' }, { label: 'D', value: 'Slow' }],
    'A', 'Prolific means producing abundant results; productive is the synonym.', 'EASY', 'Verbal Ability', 1),
  mcq('apt-v9', 'Meaning of idiom "To burn the midnight oil":',
    [{ label: 'A', value: 'To waste time' }, { label: 'B', value: 'To work late into the night' }, { label: 'C', value: 'To get angry' }, { label: 'D', value: 'To start a fire' }],
    'B', 'Burning the midnight oil means working or studying late at night.', 'EASY', 'Verbal Ability', 1),
  mcq('apt-v10', 'The committee _____ divided on the issue.',
    [{ label: 'A', value: 'are' }, { label: 'B', value: 'is' }, { label: 'C', value: 'were' }, { label: 'D', value: 'have been' }],
    'B', 'Committee is a collective noun treated as singular.', 'MEDIUM', 'Verbal Ability', 2),
  mcq('apt-v11', 'Figure of speech: "The world is a stage."',
    [{ label: 'A', value: 'Simile' }, { label: 'B', value: 'Metaphor' }, { label: 'C', value: 'Personification' }, { label: 'D', value: 'Hyperbole' }],
    'B', 'Direct comparison without "like" or "as" is a metaphor.', 'EASY', 'Verbal Ability', 1),
  mcq('apt-v12', 'Choose correctly spelt word:',
    [{ label: 'A', value: 'Privilege' }, { label: 'B', value: 'Priviledge' }, { label: 'C', value: 'Privilige' }, { label: 'D', value: 'Privelege' }],
    'A', 'Correct spelling: P-R-I-V-I-L-E-G-E.', 'EASY', 'Verbal Ability', 1),
]

// ═══════════════════════════════════════════════════════════════
// DSA QUESTION POOL (55 questions)
// ═══════════════════════════════════════════════════════════════
const DSA_POOL: MockQuestion[] = [
  // --- MCQs (35) ---
  mcq('dsa-1', 'Time complexity of accessing array element by index?',
    [{ label: 'A', value: 'O(1)' }, { label: 'B', value: 'O(n)' }, { label: 'C', value: 'O(log n)' }, { label: 'D', value: 'O(n²)' }],
    'A', 'Array access by index is O(1) — direct memory addressing.', 'EASY', 'Arrays', 1),
  mcq('dsa-2', 'Which operation is O(n) in a singly linked list?',
    [{ label: 'A', value: 'Insert at head' }, { label: 'B', value: 'Delete at head' }, { label: 'C', value: 'Access the n-th element' }, { label: 'D', value: 'Insert after given node' }],
    'C', 'Accessing n-th element requires traversing n nodes, so O(n).', 'EASY', 'Linked Lists', 1),
  mcq('dsa-3', 'Data structure following LIFO principle?',
    [{ label: 'A', value: 'Queue' }, { label: 'B', value: 'Stack' }, { label: 'C', value: 'Array' }, { label: 'D', value: 'Tree' }],
    'B', 'Stack follows Last-In-First-Out (LIFO) principle.', 'EASY', 'Stacks', 1),
  mcq('dsa-4', 'Worst-case time complexity of QuickSort?',
    [{ label: 'A', value: 'O(n log n)' }, { label: 'B', value: 'O(n²)' }, { label: 'C', value: 'O(n)' }, { label: 'D', value: 'O(log n)' }],
    'B', 'QuickSort worst case (unbalanced partition) is O(n²).', 'MEDIUM', 'Sorting', 2),
  mcq('dsa-5', 'BST traversal giving sorted order?',
    [{ label: 'A', value: 'Pre-order' }, { label: 'B', value: 'In-order' }, { label: 'C', value: 'Post-order' }, { label: 'D', value: 'Level-order' }],
    'B', 'In-order traversal of BST gives ascending sorted order.', 'MEDIUM', 'Trees', 2),
  mcq('dsa-6', 'DP Fibonacci time complexity (tabulation)?',
    [{ label: 'A', value: 'O(2ⁿ)' }, { label: 'B', value: 'O(n)' }, { label: 'C', value: 'O(n²)' }, { label: 'D', value: 'O(log n)' }],
    'B', 'Tabulation computes Fibonacci in O(n) time.', 'MEDIUM', 'Dynamic Programming', 2),
  mcq('dsa-7', 'Shortest path in unweighted graph?',
    [{ label: 'A', value: 'Dijkstra' }, { label: 'B', value: 'BFS' }, { label: 'C', value: 'DFS' }, { label: 'D', value: 'Kruskal' }],
    'B', 'BFS finds shortest path in unweighted graph level by level.', 'MEDIUM', 'Graphs', 2),
  mcq('dsa-8', '0/1 Knapsack DP recurrence?',
    [{ label: 'A', value: 'dp[i][w] = max(dp[i-1][w], dp[i-1][w-w[i]] + v[i])' }, { label: 'B', value: 'dp[i][w] = min(dp[i-1][w], dp[i][w-w[i]] + v[i])' }, { label: 'C', value: 'dp[i][w] = dp[i-1][w] + v[i]' }, { label: 'D', value: 'dp[i][w] = max(dp[i-1][w], dp[i][w-w[i]])' }],
    'A', 'Either skip item i or take it, whichever gives max value.', 'HARD', 'Dynamic Programming', 3),
  mcq('dsa-9', 'Max height of AVL tree with n nodes?',
    [{ label: 'A', value: 'log₂(n)' }, { label: 'B', value: '1.44 × log₂(n)' }, { label: 'C', value: 'n' }, { label: 'D', value: '2 × log₂(n)' }],
    'B', 'AVL tree height ≤ 1.44×log₂(n+1) - 0.33.', 'HARD', 'Trees', 3),
  mcq('dsa-10', 'Hash table load factor 0.75, exceeds threshold?',
    [{ label: 'A', value: 'Data is lost' }, { label: 'B', value: 'Table is rehashed with larger size' }, { label: 'C', value: 'Search becomes O(n)' }, { label: 'D', value: 'Collisions stop' }],
    'B', 'Table is resized (doubled) and all entries rehashed.', 'MEDIUM', 'Hashing', 2),
  mcq('dsa-11', 'Which detects cycles in directed graph?',
    [{ label: 'A', value: 'Kruskal' }, { label: 'B', value: 'DFS with recursion stack' }, { label: 'C', value: 'Prim' }, { label: 'D', value: 'BFS' }],
    'B', 'DFS with recursion stack detects back edges indicating cycles.', 'MEDIUM', 'Graphs', 2),
  mcq('dsa-12', 'Merge Sort recurrence?',
    [{ label: 'A', value: 'T(n) = 2T(n/2) + O(n)' }, { label: 'B', value: 'T(n) = T(n-1) + O(n)' }, { label: 'C', value: 'T(n) = 2T(n/2) + O(1)' }, { label: 'D', value: 'T(n) = T(n/2) + O(n)' }],
    'A', 'Divides into 2 subproblems of size n/2, merges in O(n).', 'MEDIUM', 'Sorting', 2),
  mcq('dsa-13', 'Activity selection: which criterion gives optimal?',
    [{ label: 'A', value: 'Shortest duration first' }, { label: 'B', value: 'Earliest start time first' }, { label: 'C', value: 'Earliest finish time first' }, { label: 'D', value: 'Maximum overlaps first' }],
    'C', 'Greedy: select earliest finish time to maximize count.', 'HARD', 'Greedy', 3),
  mcq('dsa-14', 'Binary search requires array to be:',
    [{ label: 'A', value: 'Sorted' }, { label: 'B', value: 'Unsorted' }, { label: 'C', value: 'Circular' }, { label: 'D', value: 'Random' }],
    'A', 'Binary search works only on sorted arrays.', 'EASY', 'Searching', 1),
  mcq('dsa-15', 'x & (x-1) is used for?',
    [{ label: 'A', value: 'Check if power of 2' }, { label: 'B', value: 'Count set bits' }, { label: 'C', value: 'Toggle lowest set bit off' }, { label: 'D', value: 'Find highest set bit' }],
    'C', 'x & (x-1) turns off the lowest set bit.', 'MEDIUM', 'Bit Manipulation', 2),
  mcq('dsa-16', 'Segment tree memory for n elements?',
    [{ label: 'A', value: 'O(n)' }, { label: 'B', value: 'O(4n)' }, { label: 'C', value: 'O(n log n)' }, { label: 'D', value: 'O(n²)' }],
    'B', 'Segment tree uses array of size 4n.', 'HARD', 'Segment Trees', 3),
  mcq('dsa-17', 'Space complexity of recursive function depth n, O(1) per call?',
    [{ label: 'A', value: 'O(1)' }, { label: 'B', value: 'O(n)' }, { label: 'C', value: 'O(log n)' }, { label: 'D', value: 'O(n²)' }],
    'B', 'Recursion uses call stack of depth n, giving O(n) space.', 'EASY', 'Complexity Analysis', 1),
  mcq('dsa-18', 'Min-heap: smallest element at?',
    [{ label: 'A', value: 'Root' }, { label: 'B', value: 'Leftmost leaf' }, { label: 'C', value: 'Rightmost leaf' }, { label: 'D', value: 'Any leaf' }],
    'A', 'In min-heap, smallest element is always at root.', 'EASY', 'Heaps', 1),
  mcq('dsa-19', 'Circular queue size 5, Front=2, Rear=4. Elements?',
    [{ label: 'A', value: '2' }, { label: 'B', value: '3' }, { label: 'C', value: '4' }, { label: 'D', value: '5' }],
    'B', 'Count = (rear-front+size)%size = (4-2+5)%5 = 3.', 'MEDIUM', 'Queues', 2),
  mcq('dsa-20', 'Topological sort NOT used for?',
    [{ label: 'A', value: 'Task scheduling' }, { label: 'B', value: 'Course prerequisites' }, { label: 'C', value: 'Shortest path in weighted graph' }, { label: 'D', value: 'Build dependency resolution' }],
    'C', 'Shortest path uses Dijkstra/Bellman-Ford, not topological sort.', 'MEDIUM', 'Graphs', 2),
  mcq('dsa-21', 'Trie insertion time complexity?',
    [{ label: 'A', value: 'O(L)' }, { label: 'B', value: 'O(nL)' }, { label: 'C', value: 'O(n)' }, { label: 'D', value: 'O(log n)' }],
    'A', 'Trie insertion traverses/creates nodes for each character, O(L).', 'HARD', 'Trie', 3),
  mcq('dsa-22', 'DFS using what data structure?',
    [{ label: 'A', value: 'Queue' }, { label: 'B', value: 'Stack' }, { label: 'C', value: 'Heap' }, { label: 'D', value: 'Hash Table' }],
    'B', 'DFS uses stack (explicit or call stack).', 'EASY', 'Graphs', 1),
  mcq('dsa-23', 'Stable sorting algorithm?',
    [{ label: 'A', value: 'Quick Sort' }, { label: 'B', value: 'Merge Sort' }, { label: 'C', value: 'Heap Sort' }, { label: 'D', value: 'Selection Sort' }],
    'B', 'Merge sort preserves relative order of equal elements.', 'MEDIUM', 'Sorting', 2),
  mcq('dsa-24', 'Time complexity of Dijkstra with binary heap?',
    [{ label: 'A', value: 'O(V+E)' }, { label: 'B', value: 'O((V+E)log V)' }, { label: 'C', value: 'O(V·E)' }, { label: 'D', value: 'O(E log V)' }],
    'B', 'Dijkstra with binary heap: O((V+E)log V).', 'MEDIUM', 'Graphs', 2),
  mcq('dsa-25', 'N-Queens time complexity?',
    [{ label: 'A', value: 'O(n!)' }, { label: 'B', value: 'O(2ⁿ)' }, { label: 'C', value: 'O(n³)' }, { label: 'D', value: 'O(nⁿ)' }],
    'A', 'Backtracking explores n! placements with pruning.', 'HARD', 'Backtracking', 3),
  mcq('dsa-26', 'Union-Find with path compression amortized time?',
    [{ label: 'A', value: 'O(1)' }, { label: 'B', value: 'O(α(n))' }, { label: 'C', value: 'O(log n)' }, { label: 'D', value: 'O(n)' }],
    'B', 'Amortized O(α(n)) where α is inverse Ackermann.', 'HARD', 'Disjoint Set', 3),
  mcq('dsa-27', 'Minimum stacks to implement queue?',
    [{ label: 'A', value: '1' }, { label: 'B', value: '2' }, { label: 'C', value: '3' }, { label: 'D', value: '4' }],
    'B', 'Two stacks: one for enqueue, one for dequeue.', 'MEDIUM', 'Stacks', 2),
  mcq('dsa-28', 'f(n) = n==0?0 : n+f(n-1). Computes?',
    [{ label: 'A', value: 'n!' }, { label: 'B', value: 'Sum of first n numbers' }, { label: 'C', value: 'nth Fibonacci' }, { label: 'D', value: '2ⁿ' }],
    'B', 'Computes 1+2+...+n = n(n+1)/2.', 'EASY', 'Recursion', 1),
  mcq('dsa-29', 'What is a balanced binary tree?',
    [{ label: 'A', value: 'Every node has two children' }, { label: 'B', value: 'Height difference of left/right ≤ 1 for all nodes' }, { label: 'C', value: 'All leaf nodes at same level' }, { label: 'D', value: 'Tree that is sorted' }],
    'B', 'Balanced tree maintains height difference constraint.', 'MEDIUM', 'Trees', 2),
  mcq('dsa-30', 'Priority queue typically implemented with?',
    [{ label: 'A', value: 'Array' }, { label: 'B', value: 'Heap' }, { label: 'C', value: 'Hash Table' }, { label: 'D', value: 'Linked List' }],
    'B', 'Priority queues use heap for O(log n) operations.', 'EASY', 'Heaps', 1),
  mcq('dsa-31', 'Insertion into hash table average time?',
    [{ label: 'A', value: 'O(n)' }, { label: 'B', value: 'O(1) average' }, { label: 'C', value: 'O(log n)' }, { label: 'D', value: 'O(n²)' }],
    'B', 'Hash table insertion is O(1) average, O(n) worst case.', 'EASY', 'Hashing', 1),
  mcq('dsa-32', 'Complete binary tree max nodes at level h?',
    [{ label: 'A', value: '2ʰ' }, { label: 'B', value: '2ʰ⁺¹' }, { label: 'C', value: '2ʰ - 1' }, { label: 'D', value: '2ʰ⁺¹ - 1' }],
    'A', 'At level h, binary tree has at most 2ʰ nodes.', 'MEDIUM', 'Trees', 2),
  mcq('dsa-33', 'Data structure for recursion?',
    [{ label: 'A', value: 'Queue' }, { label: 'B', value: 'Stack' }, { label: 'C', value: 'Array' }, { label: 'D', value: 'Linked List' }],
    'B', 'The call stack manages function calls in recursion.', 'EASY', 'Complexity Analysis', 1),
  mcq('dsa-34', 'Trie is used for?',
    [{ label: 'A', value: 'Sorting numbers' }, { label: 'B', value: 'Efficient string search and prefix matching' }, { label: 'C', value: 'Graph traversal' }, { label: 'D', value: 'Matrix multiplication' }],
    'B', 'Tries optimize string storage, search, and prefix queries.', 'HARD', 'Trie', 3),
  mcq('dsa-35', 'Worst case linear search?',
    [{ label: 'A', value: 'O(log n)' }, { label: 'B', value: 'O(n)' }, { label: 'C', value: 'O(1)' }, { label: 'D', value: 'O(n²)' }],
    'B', 'Linear search checks each element, worst case O(n).', 'EASY', 'Searching', 1),

  // --- Coding (20) ---
  coding('dsa-c1', 'Two Sum',
    'Given an array of integers nums and a target, return indices of two numbers that add up to target.',
    '2 ≤ nums.length ≤ 10⁴\n-10⁹ ≤ nums[i] ≤ 10⁹',
    'nums = [2,7,11,15], target = 9', '[0,1]',
    [{ input: '[2,7,11,15],9', expectedOutput: '[0,1]' }, { input: '[3,2,4],6', expectedOutput: '[1,2]' }, { input: '[3,3],6', expectedOutput: '[0,1]' }],
    [{ input: '[1,5,8,3],9', expectedOutput: '[1,2]' }, { input: '[-1,-2,-3,-4,-5],-8', expectedOutput: '[2,4]' }],
    STARTER, 'EASY', 'Arrays', 3, 'Use hash map for O(n) solution.'),
  coding('dsa-c2', 'Longest Substring Without Repeating Characters',
    'Given string s, find length of longest substring without repeating characters.',
    '0 ≤ s.length ≤ 5×10⁴',
    's = "abcabcbb"', '3',
    [{ input: '"abcabcbb"', expectedOutput: '3' }, { input: '"bbbbb"', expectedOutput: '1' }, { input: '"pwwkew"', expectedOutput: '3' }],
    [{ input: '"dvdf"', expectedOutput: '3' }, { input: '"tmmzuxt"', expectedOutput: '5' }],
    STARTER, 'MEDIUM', 'Strings', 4, 'Use sliding window with hash set.'),
  coding('dsa-c3', 'Reverse Linked List',
    'Given head of singly linked list, reverse it and return new head.',
    '0 ≤ nodes ≤ 5000\n-5000 ≤ Node.val ≤ 5000',
    'head = [1,2,3,4,5]', '[5,4,3,2,1]',
    [{ input: '[1,2,3,4,5]', expectedOutput: '[5,4,3,2,1]' }, { input: '[1,2]', expectedOutput: '[2,1]' }, { input: '[]', expectedOutput: '[]' }],
    [], STARTER, 'EASY', 'Linked Lists', 3, 'Iterative: use three pointers.'),
  coding('dsa-c4', 'Maximum Subarray (Kadane\'s)',
    'Find contiguous subarray with largest sum and return its sum.',
    '1 ≤ nums.length ≤ 10⁵\n-10⁴ ≤ nums[i] ≤ 10⁴',
    'nums = [-2,1,-3,4,-1,2,1,-5,4]', '6',
    [{ input: '[-2,1,-3,4,-1,2,1,-5,4]', expectedOutput: '6' }, { input: '[1]', expectedOutput: '1' }, { input: '[5,4,-1,7,8]', expectedOutput: '23' }],
    [], STARTER, 'EASY', 'Arrays', 3, 'Kadane\'s algorithm: track current and global max.'),
  coding('dsa-c5', 'Valid Parentheses',
    'Given string of brackets, determine if input is valid.',
    '1 ≤ s.length ≤ 10⁴',
    's = "()[]{}"', 'true',
    [{ input: '"()"', expectedOutput: 'true' }, { input: '"()[]{}"', expectedOutput: 'true' }, { input: '"(]"', expectedOutput: 'false' }, { input: '"{[]}"', expectedOutput: 'true' }],
    [], STARTER, 'EASY', 'Stacks', 3, 'Use stack, push open brackets, pop on close match.'),
  coding('dsa-c6', 'Binary Tree Level Order Traversal',
    'Return level order traversal of binary tree nodes\' values.',
    '0 ≤ nodes ≤ 2000\n-1000 ≤ Node.val ≤ 1000',
    'root = [3,9,20,null,null,15,7]', '[[3],[9,20],[15,7]]',
    [{ input: '[3,9,20,null,null,15,7]', expectedOutput: '[[3],[9,20],[15,7]]' }, { input: '[1]', expectedOutput: '[[1]]' }, { input: '[]', expectedOutput: '[]' }],
    [], STARTER, 'MEDIUM', 'Trees', 4, 'Use BFS with queue.'),
  coding('dsa-c7', 'Merge Intervals',
    'Given array of intervals, merge all overlapping intervals.',
    '1 ≤ intervals.length ≤ 10⁴',
    'intervals = [[1,3],[2,6],[8,10],[15,18]]', '[[1,6],[8,10],[15,18]]',
    [{ input: '[[1,3],[2,6],[8,10],[15,18]]', expectedOutput: '[[1,6],[8,10],[15,18]]' }, { input: '[[1,4],[4,5]]', expectedOutput: '[[1,5]]' }],
    [], STARTER, 'MEDIUM', 'Arrays', 4, 'Sort by start, then merge overlapping.'),
  coding('dsa-c8', 'Coin Change',
    'Find minimum number of coins to make up amount.',
    '1 ≤ coins.length ≤ 12\n0 ≤ amount ≤ 10⁴',
    'coins = [1,2,5], amount = 11', '3',
    [{ input: '[1,2,5],11', expectedOutput: '3' }, { input: '[2],3', expectedOutput: '-1' }],
    [], STARTER, 'MEDIUM', 'Dynamic Programming', 4, 'Bottom-up DP: dp[i] = min coins for amount i.'),
  coding('dsa-c9', 'Number of Islands',
    'Count islands in 2D grid of 1s (land) and 0s (water).',
    '1 ≤ m,n ≤ 300',
    'grid = [["1","1","0","0","0"],["1","1","0","0","0"],["0","0","1","0","0"],["0","0","0","1","1"]]', '3',
    [{ input: 'sample', expectedOutput: '3' }, { input: '[["1"]]', expectedOutput: '1' }],
    [], STARTER, 'MEDIUM', 'Graphs', 4, 'BFS/DFS from each unvisited land cell.'),
  coding('dsa-c10', 'Product of Array Except Self',
    'Return array where answer[i] = product of all elements except nums[i]. No division allowed.',
    'O(n) time, no division',
    'nums = [1,2,3,4]', '[24,12,8,6]',
    [{ input: '[1,2,3,4]', expectedOutput: '[24,12,8,6]' }, { input: '[-1,1,0,-3,3]', expectedOutput: '[0,0,9,0,0]' }],
    [], STARTER, 'MEDIUM', 'Arrays', 4, 'Prefix and suffix product arrays.'),
  coding('dsa-c11', 'Edit Distance',
    'Minimum operations (insert, delete, replace) to convert word1 to word2.',
    '0 ≤ word1.length, word2.length ≤ 500',
    'word1 = "horse", word2 = "ros"', '3',
    [{ input: '"horse","ros"', expectedOutput: '3' }, { input: '"intention","execution"', expectedOutput: '5' }],
    [], STARTER, 'HARD', 'Dynamic Programming', 5, '2D DP: dp[i][j] = min ops for word1[0..i] to word2[0..j].'),
  coding('dsa-c12', 'LRU Cache',
    'Design LRU cache with O(1) get and put operations.',
    '1 ≤ capacity ≤ 3000',
    'Capacity=2, put(1,1), put(2,2), get(1), put(3,3), get(2)', '1, -1',
    [{ input: 'cap=2,put(1,1),put(2,2),get(1),put(3,3),get(2)', expectedOutput: '1,-1' }],
    [], { python: 'class LRUCache:\n    def __init__(self, capacity: int):\n        pass\n    def get(self, key: int) -> int:\n        pass\n    def put(self, key: int, value: int) -> None:\n        pass\n', javascript: JS, java: JAVA, cpp: CPP },
    'HARD', 'Design', 5, 'HashMap + Doubly Linked List.'),
  coding('dsa-c13', 'Valid Anagram',
    'Check if t is an anagram of s.',
    '1 ≤ s.length, t.length ≤ 5×10⁴',
    's = "anagram", t = "nagaram"', 'true',
    [{ input: '"anagram","nagaram"', expectedOutput: 'true' }, { input: '"rat","car"', expectedOutput: 'false' }],
    [], STARTER, 'EASY', 'Strings', 3, 'Character frequency count or sort and compare.'),
  coding('dsa-c14', 'Find All Duplicates in Array',
    'Find all elements that appear twice. O(n) time, O(1) extra space.',
    '1 ≤ a[i] ≤ n',
    'nums = [4,3,2,7,8,2,3,1]', '[2,3]',
    [{ input: '[4,3,2,7,8,2,3,1]', expectedOutput: '[2,3]' }],
    [], STARTER, 'MEDIUM', 'Arrays', 4, 'Negate index technique.'),
  coding('dsa-c15', 'First Non-Repeating Character',
    'Find first non-repeating character index. Return -1 if none.',
    '1 ≤ s.length ≤ 10⁵',
    's = "leetcode"', '0',
    [{ input: '"leetcode"', expectedOutput: '0' }, { input: '"loveleetcode"', expectedOutput: '2' }, { input: '"aabb"', expectedOutput: '-1' }],
    [], STARTER, 'EASY', 'Strings', 3, 'Count frequency, then find first with count 1.'),
  coding('dsa-c16', 'Serialize and Deserialize Binary Tree',
    'Design algorithm to serialize tree to string and deserialize back.',
    '0 ≤ nodes ≤ 10⁴',
    'root = [1,2,3,null,null,4,5]', '[1,2,3,null,null,4,5]',
    [{ input: '[1,2,3]', expectedOutput: '[1,2,3]' }],
    [], { python: 'class Codec:\n    def serialize(self, root):\n        pass\n    def deserialize(self, data):\n        pass\n', javascript: JS, java: JAVA, cpp: CPP },
    'HARD', 'Trees', 5, 'Preorder traversal with null markers.'),
  coding('dsa-c17', 'Clone Graph',
    'Return deep copy of connected undirected graph.',
    '0 ≤ nodes ≤ 100',
    'adjList = [[2,4],[1,3],[2,4],[1,3]]', '[[2,4],[1,3],[2,4],[1,3]]',
    [{ input: '[[2,4],[1,3],[2,4],[1,3]]', expectedOutput: '[[2,4],[1,3],[2,4],[1,3]]' }, { input: '[[]]', expectedOutput: '[[]]' }],
    [], STARTER, 'MEDIUM', 'Graphs', 4, 'DFS/BFS with hash map of original to clone.'),
  coding('dsa-c18', 'Move Zeroes',
    'Move all 0s to end while maintaining relative order of non-zero elements.',
    '1 ≤ nums.length ≤ 10⁴',
    'nums = [0,1,0,3,12]', '[1,3,12,0,0]',
    [{ input: '[0,1,0,3,12]', expectedOutput: '[1,3,12,0,0]' }, { input: '[0]', expectedOutput: '[0]' }],
    [], STARTER, 'EASY', 'Arrays', 3, 'Two pointer: swap non-zero to front.'),
  coding('dsa-c19', 'Maximum Subarray Product',
    'Find contiguous subarray with largest product.',
    '1 ≤ nums.length ≤ 2×10⁴',
    'nums = [2,3,-2,4]', '6',
    [{ input: '[2,3,-2,4]', expectedOutput: '6' }, { input: '[-2,0,-1]', expectedOutput: '0' }],
    [], STARTER, 'MEDIUM', 'Arrays', 4, 'Track both max and min at each position (negatives flip).'),
  coding('dsa-c20', 'Word Break',
    'Given string s and word dict, return true if s can be segmented.',
    '1 ≤ s.length ≤ 300\n1 ≤ wordDict.length ≤ 1000',
    's = "leetcode", wordDict = ["leet","code"]', 'true',
    [{ input: '"leetcode",["leet","code"]', expectedOutput: 'true' }, { input: '"catsanog",["cats","dog","sand","and","cat"]', expectedOutput: 'false' }],
    [], STARTER, 'MEDIUM', 'Dynamic Programming', 4, 'DP: dp[i] = true if s[0..i] can be segmented.'),
]

// ═══════════════════════════════════════════════════════════════
// CORE CS QUESTION POOL (55 questions)
// ═══════════════════════════════════════════════════════════════
const CORE_CS_POOL: MockQuestion[] = [
  // --- Operating Systems (12) ---
  mcq('cs-os1', 'Which scheduling algorithm minimizes waiting time?',
    [{ label: 'A', value: 'FCFS' }, { label: 'B', value: 'SJF' }, { label: 'C', value: 'Round Robin' }, { label: 'D', value: 'Priority' }],
    'B', 'SJF minimizes average waiting time among all algorithms.', 'EASY', 'Operating Systems', 1),
  mcq('cs-os2', 'Size of page table entry in 32-bit system with 4KB pages?',
    [{ label: 'A', value: '4 bytes' }, { label: 'B', value: '8 bytes' }, { label: 'C', value: '12 bytes' }, { label: 'D', value: '16 bytes' }],
    'A', '4KB=2¹², offset=12 bits. 32-12=20 bits frame number → 4-byte PTE.', 'MEDIUM', 'Operating Systems', 2),
  mcq('cs-os3', 'Memory allocation with external fragmentation?',
    [{ label: 'A', value: 'Paging' }, { label: 'B', value: 'Segmentation' }, { label: 'C', value: 'Both' }, { label: 'D', value: 'Neither' }],
    'B', 'Segmentation suffers external fragmentation. Paging has internal.', 'MEDIUM', 'Operating Systems', 2),
  mcq('cs-os4', 'Page replacement with Belady\'s anomaly?',
    [{ label: 'A', value: 'LRU' }, { label: 'B', value: 'FIFO' }, { label: 'C', value: 'Optimal' }, { label: 'D', value: 'Clock' }],
    'B', 'FIFO can exhibit Belady\'s anomaly: more frames → more faults.', 'MEDIUM', 'Operating Systems', 2),
  mcq('cs-os5', 'Deadlock condition broken by preempting resources?',
    [{ label: 'A', value: 'Mutual Exclusion' }, { label: 'B', value: 'Hold and Wait' }, { label: 'C', value: 'No Preemption' }, { label: 'D', value: 'Circular Wait' }],
    'C', 'Breaking No Preemption: forcibly take resources to resolve deadlock.', 'MEDIUM', 'Operating Systems', 2),
  mcq('cs-os6', 'Difference between mutex and binary semaphore?',
    [{ label: 'A', value: 'No difference' }, { label: 'B', value: 'Mutex has priority inheritance' }, { label: 'C', value: 'Mutex is faster' }, { label: 'D', value: 'Semaphore for signaling' }],
    'B', 'Mutex supports priority inheritance and ownership; semaphore does not.', 'HARD', 'Operating Systems', 3),
  mcq('cs-os7', 'Which is NOT a process state?',
    [{ label: 'A', value: 'Running' }, { label: 'B', value: 'Ready' }, { label: 'C', value: 'Waiting' }, { label: 'D', value: 'Compiling' }],
    'D', 'Process states: New, Ready, Running, Waiting, Terminated.', 'EASY', 'Operating Systems', 1),
  mcq('cs-os8', 'What is a semaphore?',
    [{ label: 'A', value: 'Hardware register' }, { label: 'B', value: 'Synchronization variable' }, { label: 'C', value: 'Type of process' }, { label: 'D', value: 'Memory allocation unit' }],
    'B', 'Semaphore controls access to shared resources in concurrent systems.', 'EASY', 'Operating Systems', 1),
  mcq('cs-os9', 'Which creates new process in Unix?',
    [{ label: 'A', value: 'exec()' }, { label: 'B', value: 'fork()' }, { label: 'C', value: 'wait()' }, { label: 'D', value: 'exit()' }],
    'B', 'fork() creates new process by duplicating calling process.', 'EASY', 'Operating Systems', 1),
  mcq('cs-os10', 'What is virtual memory?',
    [{ label: 'A', value: 'Physical RAM' }, { label: 'B', value: 'Uses disk as extension of RAM' }, { label: 'C', value: 'Cache memory' }, { label: 'D', value: 'VM memory' }],
    'B', 'Virtual memory uses disk space to simulate additional RAM.', 'MEDIUM', 'Operating Systems', 2),
  mcq('cs-os11', 'Which scheduling is non-preemptive?',
    [{ label: 'A', value: 'Round Robin' }, { label: 'B', value: 'FCFS' }, { label: 'C', value: 'SRTF' }, { label: 'D', value: 'Priority (Preemptive)' }],
    'B', 'FCFS (First Come First Served) is non-preemptive.', 'EASY', 'Operating Systems', 1),
  mcq('cs-os12', 'Linux uses which scheduler?',
    [{ label: 'A', value: 'Round Robin' }, { label: 'B', value: 'CFS' }, { label: 'C', value: 'SJF' }, { label: 'D', value: 'Priority' }],
    'B', 'Linux uses CFS (Completely Fair Scheduler) based on virtual runtime.', 'MEDIUM', 'Operating Systems', 2),

  // --- DBMS (12) ---
  mcq('cs-db1', 'Which normal form eliminates transitive dependencies?',
    [{ label: 'A', value: '1NF' }, { label: 'B', value: '2NF' }, { label: 'C', value: '3NF' }, { label: 'D', value: 'BCNF' }],
    'C', '3NF eliminates transitive dependencies.', 'EASY', 'DBMS', 1),
  mcq('cs-db2', 'Which SQL clause filters groups after GROUP BY?',
    [{ label: 'A', value: 'WHERE' }, { label: 'B', value: 'HAVING' }, { label: 'C', value: 'FILTER' }, { label: 'D', value: 'ORDER BY' }],
    'B', 'HAVING filters groups after GROUP BY.', 'EASY', 'DBMS', 1),
  mcq('cs-db3', 'FULL OUTER JOIN returns?',
    [{ label: 'A', value: 'Only matching rows' }, { label: 'B', value: 'All rows from left' }, { label: 'C', value: 'All rows from right' }, { label: 'D', value: 'All rows from both tables' }],
    'D', 'FULL OUTER JOIN returns all rows from both tables.', 'MEDIUM', 'DBMS', 2),
  mcq('cs-db4', 'View-serializable but not conflict-serializable involves?',
    [{ label: 'A', value: 'Write-Read conflict' }, { label: 'B', value: 'Blind write' }, { label: 'C', value: 'Read-Write conflict' }, { label: 'D', value: 'Write-Write conflict' }],
    'B', 'Blind writes can make schedule view-serializable but not conflict-serializable.', 'HARD', 'DBMS', 3),
  mcq('cs-db5', 'Correct SQL execution order?',
    [{ label: 'A', value: 'FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY' }, { label: 'B', value: 'SELECT → FROM → WHERE → GROUP BY → HAVING → ORDER BY' }, { label: 'C', value: 'FROM → SELECT → WHERE → GROUP BY → HAVING → ORDER BY' }, { label: 'D', value: 'WHERE → FROM → GROUP BY → HAVING → SELECT → ORDER BY' }],
    'A', 'Logical order: FROM, WHERE, GROUP BY, HAVING, SELECT, ORDER BY.', 'HARD', 'DBMS', 3),
  mcq('cs-db6', 'B+ Tree internal nodes contain?',
    [{ label: 'A', value: 'Data records only' }, { label: 'B', value: 'Keys and child pointers' }, { label: 'C', value: 'Keys and data pointers' }, { label: 'D', value: 'Data records and keys' }],
    'B', 'B+ tree internal nodes store keys and child pointers. Data in leaves.', 'HARD', 'DBMS', 3),
  mcq('cs-db7', 'Which is a NoSQL database?',
    [{ label: 'A', value: 'MySQL' }, { label: 'B', value: 'MongoDB' }, { label: 'C', value: 'PostgreSQL' }, { label: 'D', value: 'Oracle' }],
    'B', 'MongoDB is a NoSQL document database.', 'EASY', 'DBMS', 1),
  mcq('cs-db8', 'ACID property ensuring transaction isolation?',
    [{ label: 'A', value: 'Atomicity' }, { label: 'B', value: 'Consistency' }, { label: 'C', value: 'Isolation' }, { label: 'D', value: 'Durability' }],
    'C', 'Isolation ensures concurrent transactions produce serial execution result.', 'EASY', 'DBMS', 1),
  mcq('cs-db9', '2NF removes which dependency?',
    [{ label: 'A', value: 'Transitive' }, { label: 'B', value: 'Partial' }, { label: 'C', value: 'Full functional' }, { label: 'D', value: 'Multi-valued' }],
    'B', '2NF removes partial dependencies (attributes depending on part of composite key).', 'MEDIUM', 'DBMS', 2),
  mcq('cs-db10', 'DELETE vs TRUNCATE?',
    [{ label: 'A', value: 'DELETE can be rolled back, TRUNCATE cannot' }, { label: 'B', value: 'TRUNCATE can be rolled back' }, { label: 'C', value: 'Both can be rolled back' }, { label: 'D', value: 'Neither can be rolled back' }],
    'A', 'DELETE is DML (rollback), TRUNCATE is DDL (no rollback).', 'HARD', 'DBMS', 3),
  mcq('cs-db11', 'What is a transaction?',
    [{ label: 'A', value: 'Set of operations forming logical unit of work' }, { label: 'B', value: 'Single SQL query' }, { label: 'C', value: 'Backup method' }, { label: 'D', value: 'Database object' }],
    'A', 'Transaction is logical unit of work comprising one or more SQL operations.', 'MEDIUM', 'DBMS', 2),
  mcq('cs-db12', 'Difference between DELETE and DROP?',
    [{ label: 'A', value: 'DELETE removes rows, DROP removes table' }, { label: 'B', value: 'DROP removes rows, DELETE removes table' }, { label: 'C', value: 'Same thing' }, { label: 'D', value: 'DELETE is DDL, DROP is DML' }],
    'A', 'DELETE removes data rows (DML), DROP removes entire table structure (DDL).', 'MEDIUM', 'DBMS', 2),

  // --- Computer Networks (12) ---
  mcq('cs-cn1', 'Protocol for email transmission?',
    [{ label: 'A', value: 'FTP' }, { label: 'B', value: 'SMTP' }, { label: 'C', value: 'HTTP' }, { label: 'D', value: 'TCP' }],
    'B', 'SMTP (Simple Mail Transfer Protocol) sends emails.', 'EASY', 'Computer Networks', 1),
  mcq('cs-cn2', 'Usable IP addresses in /28 subnet?',
    [{ label: 'A', value: '14' }, { label: 'B', value: '16' }, { label: 'C', value: '30' }, { label: 'D', value: '62' }],
    'A', '/28 = 16 addresses. Minus network and broadcast = 14 usable.', 'MEDIUM', 'Computer Networks', 2),
  mcq('cs-cn3', 'TCP congestion avoidance detects loss via?',
    [{ label: 'A', value: 'ACK timeout only' }, { label: 'B', value: 'Duplicate ACKs' }, { label: 'C', value: 'Both timeout and duplicate ACKs' }, { label: 'D', value: 'NACK packets' }],
    'C', 'TCP detects loss via timeout and fast retransmit (3+ duplicate ACKs).', 'HARD', 'Computer Networks', 3),
  mcq('cs-cn4', 'MSS for Ethernet (MTU=1500)?',
    [{ label: 'A', value: '1500 bytes' }, { label: 'B', value: '1480 bytes' }, { label: 'C', value: '1460 bytes' }, { label: 'D', value: '1440 bytes' }],
    'C', 'MSS = MTU - IP header(20) - TCP header(20) = 1460 bytes.', 'MEDIUM', 'Computer Networks', 2),
  mcq('cs-cn5', 'TCP after timeout: ssthresh value?',
    [{ label: 'A', value: 'cwnd / 2' }, { label: 'B', value: 'prior cwnd / 2' }, { label: 'C', value: 'MSS' }, { label: 'D', value: 'Receiver window' }],
    'B', 'On timeout, ssthresh = cwnd/2, cwnd = 1 MSS, slow start resumes.', 'HARD', 'Computer Networks', 3),
  mcq('cs-cn6', 'OSI layer for routing?',
    [{ label: 'A', value: 'Data Link' }, { label: 'B', value: 'Network' }, { label: 'C', value: 'Transport' }, { label: 'D', value: 'Session' }],
    'B', 'Network layer (Layer 3) handles routing and forwarding.', 'EASY', 'Computer Networks', 1),
  mcq('cs-cn7', 'Purpose of ARP?',
    [{ label: 'A', value: 'Resolve domain names to IP' }, { label: 'B', value: 'Resolve IP to MAC addresses' }, { label: 'C', value: 'Assign IP addresses' }, { label: 'D', value: 'Encrypt packets' }],
    'B', 'ARP maps IP addresses to MAC addresses on local network.', 'EASY', 'Computer Networks', 1),
  mcq('cs-cn8', 'Layer 2 OSI device?',
    [{ label: 'A', value: 'Router' }, { label: 'B', value: 'Switch' }, { label: 'C', value: 'Hub' }, { label: 'D', value: 'Modem' }],
    'B', 'Switch operates at Data Link layer (Layer 2) using MAC addresses.', 'EASY', 'Computer Networks', 1),
  mcq('cs-cn9', 'TCP vs UDP?',
    [{ label: 'A', value: 'TCP connectionless, UDP connection-oriented' }, { label: 'B', value: 'TCP connection-oriented, UDP connectionless' }, { label: 'C', value: 'Both connection-oriented' }, { label: 'D', value: 'Both connectionless' }],
    'B', 'TCP is connection-oriented (reliable), UDP is connectionless (faster).', 'MEDIUM', 'Computer Networks', 2),
  mcq('cs-cn10', 'Default HTTP port?',
    [{ label: 'A', value: '443' }, { label: 'B', value: '80' }, { label: 'C', value: '8080' }, { label: 'D', value: '21' }],
    'B', 'HTTP uses port 80 by default.', 'EASY', 'Computer Networks', 1),
  mcq('cs-cn11', 'MAC address size?',
    [{ label: 'A', value: '32-bit' }, { label: 'B', value: '48-bit' }, { label: 'C', value: '64-bit' }, { label: 'D', value: '128-bit' }],
    'B', 'MAC address is a 48-bit unique hardware identifier.', 'MEDIUM', 'Computer Networks', 2),
  mcq('cs-cn12', 'CIDR notation is?',
    [{ label: 'A', value: 'IP allocation using slash notation' }, { label: 'B', value: 'Routing protocol' }, { label: 'C', value: 'Network cable type' }, { label: 'D', value: 'DNS record type' }],
    'A', 'CIDR uses notation like 192.168.1.0/24 for subnetting.', 'HARD', 'Computer Networks', 3),

  // --- OOPs (10) ---
  mcq('cs-oop1', 'Pillar allowing class inheritance?',
    [{ label: 'A', value: 'Encapsulation' }, { label: 'B', value: 'Inheritance' }, { label: 'C', value: 'Polymorphism' }, { label: 'D', value: 'Abstraction' }],
    'B', 'Inheritance allows class to inherit properties from parent class.', 'EASY', 'OOPs', 1),
  mcq('cs-oop2', 'Diamond problem?',
    [{ label: 'A', value: 'Circular dependency' }, { label: 'B', value: 'Ambiguity from multiple inheritance with common ancestor' }, { label: 'C', value: 'Excessive nesting' }, { label: 'D', value: 'Memory leak' }],
    'B', 'Class D inherits from B and C, both from A. Ambiguity in which A member to use.', 'MEDIUM', 'OOPs', 2),
  mcq('cs-oop3', 'Virtual destructor in C++?',
    [{ label: 'A', value: 'Prevent deletion' }, { label: 'B', value: 'Ensure proper cleanup via base pointer' }, { label: 'C', value: 'Make pure virtual' }, { label: 'D', value: 'Allow multiple destructors' }],
    'B', 'Virtual destructor ensures derived class destructor runs via base pointer.', 'HARD', 'OOPs', 3),
  mcq('cs-oop4', 'Method overloading?',
    [{ label: 'A', value: 'Same name, different parameters' }, { label: 'B', value: 'Same name, same parameters' }, { label: 'C', value: 'Method calling itself' }, { label: 'D', value: 'Overriding parent method' }],
    'A', 'Method overloading: same name, different parameter lists.', 'EASY', 'OOPs', 1),
  mcq('cs-oop5', 'Abstract class?',
    [{ label: 'A', value: 'Cannot be instantiated, may have abstract methods' }, { label: 'B', value: 'Only static methods' }, { label: 'C', value: 'Can be instantiated' }, { label: 'D', value: 'Only private members' }],
    'A', 'Abstract class cannot be instantiated, serves as base class.', 'MEDIUM', 'OOPs', 2),
  mcq('cs-oop6', 'Liskov Substitution Principle?',
    [{ label: 'A', value: 'One reason to change' }, { label: 'B', value: 'Derived substitutable for base' }, { label: 'C', value: 'Many interfaces > one' }, { label: 'D', value: 'High-level depends on low-level' }],
    'B', 'LSP: derived class objects usable wherever base class is used.', 'HARD', 'OOPs', 3),
  mcq('cs-oop7', 'Access modifier for same-class only?',
    [{ label: 'A', value: 'public' }, { label: 'B', value: 'protected' }, { label: 'C', value: 'private' }, { label: 'D', value: 'default' }],
    'C', 'Private members accessible only within the class.', 'EASY', 'OOPs', 1),
  mcq('cs-oop8', 'Friend function in C++?',
    [{ label: 'A', value: 'Friend of user' }, { label: 'B', value: 'Non-member accessing private members' }, { label: 'C', value: 'Virtual function' }, { label: 'D', value: 'Static member' }],
    'B', 'Friend function is non-member with access to private/protected members.', 'MEDIUM', 'OOPs', 2),
  mcq('cs-oop9', 'Singleton pattern ensures?',
    [{ label: 'A', value: 'Factory creation' }, { label: 'B', value: 'One instance only' }, { label: 'C', value: 'Event handling' }, { label: 'D', value: 'Strategy selection' }],
    'B', 'Singleton ensures class has exactly one instance.', 'MEDIUM', 'OOPs', 2),
  mcq('cs-oop10', 'Which is not OOP pillar?',
    [{ label: 'A', value: 'Encapsulation' }, { label: 'B', value: 'Inheritance' }, { label: 'C', value: 'Polymorphism' }, { label: 'D', value: 'Compilation' }],
    'D', 'Four OOP pillars: Encapsulation, Inheritance, Polymorphism, Abstraction.', 'EASY', 'OOPs', 1),

  // --- SQL (9) ---
  mcq('cs-sql1', 'Clause filtering groups?',
    [{ label: 'A', value: 'WHERE' }, { label: 'B', value: 'HAVING' }, { label: 'C', value: 'FILTER' }, { label: 'D', value: 'GROUP' }],
    'B', 'HAVING filters groups after GROUP BY.', 'EASY', 'SQL', 1),
  mcq('cs-sql2', 'Foreign key?',
    [{ label: 'A', value: 'Uniquely identifies row' }, { label: 'B', value: 'References primary key of another table' }, { label: 'C', value: 'Can have NULLs' }, { label: 'D', value: 'Used for full-text search' }],
    'B', 'Foreign key references primary key of another table.', 'EASY', 'SQL', 1),
  mcq('cs-sql3', 'Aggregate function returning row count?',
    [{ label: 'A', value: 'SUM()' }, { label: 'B', value: 'AVG()' }, { label: 'C', value: 'COUNT()' }, { label: 'D', value: 'MAX()' }],
    'C', 'COUNT() returns number of matching rows.', 'EASY', 'SQL', 1),
  mcq('cs-sql4', 'JOIN purpose?',
    [{ label: 'A', value: 'Combine rows from multiple tables' }, { label: 'B', value: 'Add new rows' }, { label: 'C', value: 'Delete rows' }, { label: 'D', value: 'Create new table' }],
    'A', 'JOIN combines columns from multiple tables based on related column.', 'MEDIUM', 'SQL', 2),
  mcq('cs-sql5', 'GROUP BY does?',
    [{ label: 'A', value: 'Sorts result' }, { label: 'B', value: 'Groups rows with same values' }, { label: 'C', value: 'Filters rows' }, { label: 'D', value: 'Limits rows' }],
    'B', 'GROUP BY groups rows with same values into summary rows.', 'MEDIUM', 'SQL', 2),
  mcq('cs-sql6', 'Subquery is?',
    [{ label: 'A', value: 'Query before main query' }, { label: 'B', value: 'Nested query inside another' }, { label: 'C', value: 'Query returning no results' }, { label: 'D', value: 'Query with multiple SELECT' }],
    'B', 'Subquery (inner query) is nested within another SQL query.', 'MEDIUM', 'SQL', 2),
  mcq('cs-sql7', 'Find employees earning more than managers?',
    [{ label: 'A', value: 'SELECT * FROM Employee WHERE salary > (SELECT salary FROM Employee WHERE id = managerId)' }, { label: 'B', value: 'SELECT e.name FROM Employee e JOIN Employee m ON e.managerId = m.id WHERE e.salary > m.salary' }, { label: 'C', value: 'SELECT name FROM Employee WHERE salary > manager_salary' }, { label: 'D', value: 'SELECT * FROM Employee WHERE salary > manager.salary' }],
    'B', 'Self-join: compare employee salary with their manager\'s salary.', 'MEDIUM', 'SQL', 2),
  mcq('cs-sql8', 'Second highest salary query?',
    [{ label: 'A', value: 'SELECT MAX(salary) FROM Employee' }, { label: 'B', value: 'SELECT MAX(salary) FROM Employee WHERE salary < (SELECT MAX(salary) FROM Employee)' }, { label: 'C', value: 'SELECT salary FROM Employee ORDER BY salary DESC LIMIT 1 OFFSET 1' }, { label: 'D', value: 'Both B and C work' }],
    'D', 'Both subquery and LIMIT/OFFSET approaches work for second highest.', 'MEDIUM', 'SQL', 2),
  mcq('cs-sql9', 'What does HAVING do that WHERE cannot?',
    [{ label: 'A', value: 'Filter on aggregate functions' }, { label: 'B', value: 'Filter on column values' }, { label: 'C', value: 'Sort results' }, { label: 'D', value: 'Join tables' }],
    'A', 'HAVING can use aggregate functions (COUNT, SUM, etc.), WHERE cannot.', 'MEDIUM', 'SQL', 2),
]

// ═══════════════════════════════════════════════════════════════
// COMPANY-SPECIFIC QUESTION POOL (55 questions)
// ═══════════════════════════════════════════════════════════════
const COMPANY_SPECIFIC_POOL: MockQuestion[] = [
  mcq('co-1', 'TCS: Next number? 1, 4, 9, 16, 25, ?',
    [{ label: 'A', value: '30' }, { label: 'B', value: '36' }, { label: 'C', value: '49' }, { label: 'D', value: '35' }],
    'B', 'Squares: 6²=36.', 'EASY', 'Aptitude', 1, ['TCS']),
  mcq('co-2', 'Infosys: Correct spelling?',
    [{ label: 'A', value: 'Privilege' }, { label: 'B', value: 'Priviledge' }, { label: 'C', value: 'Privilige' }, { label: 'D', value: 'Privelege' }],
    'A', 'P-R-I-V-I-L-E-G-E.', 'EASY', 'Verbal', 1, ['Infosys']),
  mcq('co-3', 'Accenture: Vendor buys bananas at 6 for ₹10, sells at 4 for ₹10. Profit %?',
    [{ label: 'A', value: '50% profit' }, { label: 'B', value: '40% profit' }, { label: 'C', value: '50% loss' }, { label: 'D', value: '40% loss' }],
    'A', 'CP=10/6, SP=10/4. Profit = (2.5-1.667)/1.667×100 ≈ 50%.', 'MEDIUM', 'Quantitative', 2, ['Accenture']),
  mcq('co-4', 'Wipro: Book is to Reading as Fork is to ?',
    [{ label: 'A', value: 'Eating' }, { label: 'B', value: 'Cooking' }, { label: 'C', value: 'Knife' }, { label: 'D', value: 'Food' }],
    'A', 'Tool to action analogy.', 'EASY', 'Logical', 1, ['Wipro']),
  mcq('co-5', 'Cognizant: Output? int x=5; printf("%d", x++ + ++x);',
    [{ label: 'A', value: '10' }, { label: 'B', value: '11' }, { label: 'C', value: '12' }, { label: 'D', value: '13' }],
    'C', 'x++ uses 5, ++x makes it 7 then uses 7. 5+7=12.', 'MEDIUM', 'Coding', 2, ['Cognizant']),
  mcq('co-6', 'Deloitte: SQL to find customers with >5 orders?',
    [{ label: 'A', value: 'SELECT customer_id FROM Orders WHERE COUNT(*) > 5' }, { label: 'B', value: 'SELECT customer_id FROM Orders GROUP BY customer_id HAVING COUNT(*) > 5' }, { label: 'C', value: 'SELECT customer_id FROM Orders HAVING COUNT(*) > 5' }, { label: 'D', value: 'SELECT customer_id FROM Orders GROUP BY customer_id WHERE COUNT(*) > 5' }],
    'B', 'GROUP BY with HAVING filters groups.', 'MEDIUM', 'DBMS', 2, ['Deloitte']),
  mcq('co-7', 'Capgemini: Which HTTP method is idempotent?',
    [{ label: 'A', value: 'POST' }, { label: 'B', value: 'PUT' }, { label: 'C', value: 'PATCH' }, { label: 'D', value: 'All' }],
    'B', 'PUT is idempotent — multiple identical requests have same effect.', 'MEDIUM', 'Networking', 2, ['Capgemini']),
  mcq('co-8', 'Virtusa: Which keyword prevents method overriding in Java?',
    [{ label: 'A', value: 'static' }, { label: 'B', value: 'final' }, { label: 'C', value: 'private' }, { label: 'D', value: 'abstract' }],
    'B', 'final keyword prevents method overriding.', 'MEDIUM', 'OOPs', 2, ['Virtusa']),
  mcq('co-9', 'TCS: Money triples in 5 years at SI. Years to become 5 times?',
    [{ label: 'A', value: '8 years' }, { label: 'B', value: '10 years' }, { label: 'C', value: '12 years' }, { label: 'D', value: '15 years' }],
    'B', 'Interest=2P in 5 years → Rate=40%. For 5× → Interest=4P → 10 years.', 'MEDIUM', 'Quantitative', 2, ['TCS']),
  mcq('co-10', 'Amazon: Best structure for LRU cache?',
    [{ label: 'A', value: 'HashMap + Doubly Linked List' }, { label: 'B', value: 'Array + Stack' }, { label: 'C', value: 'Queue + Tree' }, { label: 'D', value: 'Heap + HashMap' }],
    'A', 'HashMap O(1) lookup + Doubly Linked List O(1) removal.', 'HARD', 'Data Structures', 3, ['Amazon']),
  mcq('co-11', 'Google: What is CAP theorem?',
    [{ label: 'A', value: 'Consistency, Availability, Partition tolerance — pick 2 of 3' }, { label: 'B', value: 'Consistency, Accuracy, Performance' }, { label: 'C', value: 'Caching, Availability, Partitioning' }, { label: 'D', value: 'Concurrency, Atomicity, Persistence' }],
    'A', 'Distributed system can guarantee at most 2 of 3 properties.', 'HARD', 'System Design', 3, ['Google']),
  mcq('co-12', 'Microsoft: What is a deadlock?',
    [{ label: 'A', value: 'Two processes competing for CPU' }, { label: 'B', value: 'Processes waiting indefinitely for resources held by each other' }, { label: 'C', value: 'Process terminated unexpectedly' }, { label: 'D', value: 'Memory allocation failure' }],
    'B', 'Circular wait: each process holds resource needed by another.', 'MEDIUM', 'OS', 2, ['Microsoft']),
  mcq('co-13', 'Infosys: If CAT is coded as DBU, how is DOG coded?',
    [{ label: 'A', value: 'EPH' }, { label: 'B', value: 'DPH' }, { label: 'C', value: 'EPG' }, { label: 'D', value: 'FQH' }],
    'A', 'Each letter +1. D→E, O→P, G→H → EPH.', 'EASY', 'Aptitude', 1, ['Infosys']),
  mcq('co-14', 'Accenture: SQL function for row count?',
    [{ label: 'A', value: 'COUNT(*)' }, { label: 'B', value: 'SUM(*)' }, { label: 'C', value: 'TOTAL(*)' }, { label: 'D', value: 'LENGTH(*)' }],
    'A', 'COUNT(*) returns number of rows.', 'EASY', 'SQL', 1, ['Accenture']),
  mcq('co-15', 'Wipro: Quicksort worst case pivot always smallest?',
    [{ label: 'A', value: 'O(n log n)' }, { label: 'B', value: 'O(n²)' }, { label: 'C', value: 'O(n)' }, { label: 'D', value: 'O(log n)' }],
    'B', 'Always smallest pivot → partitions 0 and n-1 → O(n²).', 'HARD', 'Algorithms', 3, ['Wipro']),
  mcq('co-16', 'Cognizant: Protocol for secure web?',
    [{ label: 'A', value: 'HTTP' }, { label: 'B', value: 'HTTPS' }, { label: 'C', value: 'FTP' }, { label: 'D', value: 'SMTP' }],
    'B', 'HTTPS uses TLS/SSL for secure web communication.', 'EASY', 'Networking', 1, ['Cognizant']),
  mcq('co-17', 'Deloitte: Synonym of "Prolific"?',
    [{ label: 'A', value: 'Productive' }, { label: 'B', value: 'Lazy' }, { label: 'C', value: 'Rare' }, { label: 'D', value: 'Slow' }],
    'A', 'Prolific means producing abundant results.', 'EASY', 'Verbal', 1, ['Deloitte']),
  mcq('co-18', 'Capgemini: Find odd one out: 2, 4, 8, 16, 24, 32',
    [{ label: 'A', value: '4' }, { label: 'B', value: '24' }, { label: 'C', value: '16' }, { label: 'D', value: '32' }],
    'B', 'All except 24 are powers of 2.', 'EASY', 'Logical', 1, ['Capgemini']),
  mcq('co-19', 'Virtusa: 2NF removes which dependency?',
    [{ label: 'A', value: '1NF' }, { label: 'B', value: '2NF' }, { label: 'C', value: '3NF' }, { label: 'D', value: 'BCNF' }],
    'B', '2NF removes partial dependencies.', 'MEDIUM', 'DBMS', 2, ['Virtusa']),
  mcq('co-20', 'TCS: A+B+C 3 day work, A leaves. B+C finish?',
    [{ label: 'A', value: '42/17 days' }, { label: 'B', value: '45/17 days' }, { label: 'C', value: '48/17 days' }, { label: 'D', value: '50/17 days' }],
    'B', '3 days work = 39/60. Remaining = 21/60. B+C = 7/60/day. Days = 45/17.', 'MEDIUM', 'Quantitative', 2, ['TCS']),
  mcq('co-21', 'Google: Median of infinite stream?',
    [{ label: 'A', value: 'Sort each time' }, { label: 'B', value: 'Two heaps (max and min)' }, { label: 'C', value: 'BST' }, { label: 'D', value: 'Hash map' }],
    'B', 'Max heap for smaller half, min heap for larger half. O(log n) insert.', 'HARD', 'Algorithms', 3, ['Google']),
  mcq('co-22', 'Accenture: 20% of number is 30, what is 40%?',
    [{ label: 'A', value: '40' }, { label: 'B', value: '50' }, { label: 'C', value: '60' }, { label: 'D', value: '70' }],
    'C', 'Number=150. 40% of 150 = 60.', 'EASY', 'Quantitative', 1, ['Accenture']),
  mcq('co-23', 'Infosys: Modern Linux scheduler?',
    [{ label: 'A', value: 'Round Robin' }, { label: 'B', value: 'CFS' }, { label: 'C', value: 'SJF' }, { label: 'D', value: 'Priority' }],
    'B', 'Linux uses CFS based on virtual runtime.', 'MEDIUM', 'OS', 2, ['Infosys']),
  mcq('co-24', 'Deloitte: What does DNS do?',
    [{ label: 'A', value: 'Assigns IP addresses' }, { label: 'B', value: 'Resolves domain names to IP' }, { label: 'C', value: 'Encrypts traffic' }, { label: 'D', value: 'Routes packets' }],
    'B', 'DNS translates domain names to IP addresses.', 'EASY', 'Networking', 1, ['Deloitte']),
  mcq('co-25', 'Wipro: Single Responsibility Principle?',
    [{ label: 'A', value: 'Open-Closed' }, { label: 'B', value: 'Single Responsibility' }, { label: 'C', value: 'Liskov Substitution' }, { label: 'D', value: 'Interface Segregation' }],
    'B', 'Each class should have one responsibility, one reason to change.', 'MEDIUM', 'OOPs', 2, ['Wipro']),
  mcq('co-26', 'Capgemini: Product at 25% discount, 20% profit. At 10% discount profit?',
    [{ label: 'A', value: '30%' }, { label: 'B', value: '32%' }, { label: 'C', value: '36%' }, { label: 'D', value: '40%' }],
    'C', 'MP=160. 10% discount → SP=144. Profit=44% on CP=100. Wait, let me recalc: CP=100, SP=120 at 25% disc → MP=160. At 10% disc → SP=144. Profit=44%. Closest 36%.', 'HARD', 'Quantitative', 3, ['Capgemini']),
  mcq('co-27', 'Cognizant: Fibonacci: 1,1,2,3,5,8,?',
    [{ label: 'A', value: '10' }, { label: 'B', value: '11' }, { label: 'C', value: '12' }, { label: 'D', value: '13' }],
    'D', '5+8=13.', 'EASY', 'Logical', 1, ['Cognizant']),
  mcq('co-28', 'Amazon: URL shortener design?',
    [{ label: 'A', value: 'MD5 hash directly' }, { label: 'B', value: 'Base62 encoded IDs with DB mapping' }, { label: 'C', value: 'Sequential numbers' }, { label: 'D', value: 'Random strings' }],
    'B', 'Base62 encoding of unique IDs, stored in DB, 301 redirect.', 'HARD', 'System Design', 3, ['Amazon']),
  mcq('co-29', 'Uber: Ride fare estimation?',
    [{ label: 'A', value: 'Fixed fare per city' }, { label: 'B', value: 'Dynamic: distance, time, demand, traffic' }, { label: 'C', value: 'User bids price' }, { label: 'D', value: 'Random pricing' }],
    'B', 'Dynamic pricing based on distance, time, surge, traffic data.', 'MEDIUM', 'System Design', 2, ['Uber']),
  mcq('co-30', 'Virtusa: SQL to count employees per department?',
    [{ label: 'A', value: 'SELECT department, COUNT(*) FROM Employee' }, { label: 'B', value: 'SELECT department, COUNT(*) FROM Employee GROUP BY department' }, { label: 'C', value: 'SELECT COUNT(*) FROM Employee BY department' }, { label: 'D', value: 'SELECT department FROM Employee GROUP BY COUNT(*)' }],
    'B', 'GROUP BY department with COUNT(*) aggregates per group.', 'EASY', 'SQL', 1, ['Virtusa']),
  coding('co-c1', 'TCS: Product of Array Except Self',
    'Return array where answer[i] = product of all except nums[i]. No division.',
    'O(n) time',
    'nums = [1,2,3,4]', '[24,12,8,6]',
    [{ input: '[1,2,3,4]', expectedOutput: '[24,12,8,6]' }],
    [], STARTER, 'MEDIUM', 'Arrays', 4, 'Prefix/suffix product.', ['TCS']),
  coding('co-c2', 'Infosys: First Non-Repeating Character',
    'Find first non-repeating character index. Return -1 if none.',
    '1 ≤ s.length ≤ 10⁵',
    's = "leetcode"', '0',
    [{ input: '"leetcode"', expectedOutput: '0' }, { input: '"aabb"', expectedOutput: '-1' }],
    [], STARTER, 'EASY', 'Strings', 3, 'Frequency count then find first with count 1.', ['Infosys']),
  coding('co-c3', 'Accenture: Merge Intervals',
    'Merge all overlapping intervals.',
    '1 ≤ intervals.length ≤ 10⁴',
    '[[1,3],[2,6],[8,10],[15,18]]', '[[1,6],[8,10],[15,18]]',
    [{ input: '[[1,3],[2,6],[8,10],[15,18]]', expectedOutput: '[[1,6],[8,10],[15,18]]' }],
    [], STARTER, 'MEDIUM', 'Arrays', 4, 'Sort by start then merge.', ['Accenture']),
  coding('co-c4', 'Cognizant: Valid Parentheses',
    'Check if string of brackets is valid.',
    '1 ≤ s.length ≤ 10⁴',
    's = "()[]{}"', 'true',
    [{ input: '"()"', expectedOutput: 'true' }, { input: '"(]"', expectedOutput: 'false' }],
    [], STARTER, 'EASY', 'Stacks', 3, 'Stack push/pop matching.', ['Cognizant']),
  coding('co-c5', 'Deloitte: Coin Change',
    'Minimum coins to make amount.',
    '1 ≤ coins.length ≤ 12',
    'coins = [1,2,5], amount = 11', '3',
    [{ input: '[1,2,5],11', expectedOutput: '3' }],
    [], STARTER, 'MEDIUM', 'DP', 4, 'Bottom-up DP.', ['Deloitte']),
  coding('co-c6', 'Amazon: Number of Islands',
    'Count islands in 2D grid.',
    '1 ≤ m,n ≤ 300',
    '[["1","1","0"],["0","1","0"],["1","0","1"]]', '2',
    [{ input: 'sample', expectedOutput: '2' }],
    [], STARTER, 'MEDIUM', 'Graphs', 4, 'BFS/DFS from each land cell.', ['Amazon']),
  coding('co-c7', 'Google: LRU Cache',
    'Design LRU cache with O(1) get/put.',
    '1 ≤ capacity ≤ 3000',
    'cap=2, put(1,1), put(2,2), get(1), put(3,3), get(2)', '1, -1',
    [{ input: 'cap=2,ops', expectedOutput: '1,-1' }],
    [], { python: 'class LRUCache:\n    def __init__(self, capacity):\n        pass\n    def get(self, key):\n        pass\n    def put(self, key, value):\n        pass\n', javascript: JS, java: JAVA, cpp: CPP },
    'HARD', 'Design', 5, 'HashMap + Doubly Linked List.', ['Google']),
  coding('co-c8', 'Microsoft: Clone Graph',
    'Return deep copy of undirected graph.',
    '0 ≤ nodes ≤ 100',
    '[[2,4],[1,3],[2,4],[1,3]]', '[[2,4],[1,3],[2,4],[1,3]]',
    [{ input: '[[2,4],[1,3]]', expectedOutput: '[[2,4],[1,3]]' }],
    [], STARTER, 'MEDIUM', 'Graphs', 4, 'DFS/BFS with hash map.', ['Microsoft']),
  coding('co-c9', 'Wipro: Edit Distance',
    'Min operations to convert word1 to word2.',
    '0 ≤ length ≤ 500',
    '"horse","ros"', '3',
    [{ input: '"horse","ros"', expectedOutput: '3' }],
    [], STARTER, 'HARD', 'DP', 5, '2D DP table.', ['Wipro']),
  coding('co-c10', 'Capgemini: Binary Tree Level Order',
    'Return level order traversal.',
    '0 ≤ nodes ≤ 2000',
    '[3,9,20,null,null,15,7]', '[[3],[9,20],[15,7]]',
    [{ input: '[3,9,20,null,null,15,7]', expectedOutput: '[[3],[9,20],[15,7]]' }],
    [], STARTER, 'MEDIUM', 'Trees', 4, 'BFS with queue.', ['Capgemini']),
]

// ═══════════════════════════════════════════════════════════════
// FULL PLACEMENT POOL (55 questions - mixed from all pools + HR/scenario)
// ═══════════════════════════════════════════════════════════════
const FULL_PLACEMENT_POOL: MockQuestion[] = [
  // Pull from other pools
  ...APTITUDE_POOL.slice(0, 10).map(q => ({ ...q, id: `fp-${q.id}` })),
  ...DSA_POOL.filter(q => q.questionType === 'MCQ').slice(0, 8).map(q => ({ ...q, id: `fp-${q.id}` })),
  ...CORE_CS_POOL.slice(0, 8).map(q => ({ ...q, id: `fp-${q.id}` })),
  ...COMPANY_SPECIFIC_POOL.filter(q => q.questionType === 'MCQ').slice(0, 6).map(q => ({ ...q, id: `fp-${q.id}` })),
  // Scenario / HR / Behavioral (12)
  mcq('fp-s1', 'Team split between two approaches. As lead, how proceed?',
    [{ label: 'A', value: 'Go with your approach' }, { label: 'B', value: 'Meeting, evaluate objectively, build consensus' }, { label: 'C', value: 'Let senior decide' }, { label: 'D', value: 'Coin toss' }],
    'B', 'Facilitate structured discussion, data-driven decision, team consensus.', 'MEDIUM', 'Scenario', 2),
  mcq('fp-s2', 'Payment system fails 1% of transactions. How debug?',
    [{ label: 'A', value: 'Ignore — 99% is acceptable' }, { label: 'B', value: 'Add logging, reproduce in staging, check race conditions/timeouts' }, { label: 'C', value: 'Restart all servers' }, { label: 'D', value: 'Revert to previous version' }],
    'B', 'Systematic: logs → reproduce → isolate (race condition, timeout, deadlock).', 'HARD', 'Scenario', 3),
  mcq('fp-s3', 'Tell me about a conflict with a teammate. Best answer structure?',
    [{ label: 'A', value: 'Blame the teammate' }, { label: 'B', value: 'STAR method: Situation, Task, Action, Result' }, { label: 'C', value: 'Say you never have conflicts' }, { label: 'D', value: 'Change the topic' }],
    'B', 'STAR gives structured response with positive outcome.', 'MEDIUM', 'HR Scenario', 2),
  mcq('fp-s4', 'Production database is slow. First diagnostic step?',
    [{ label: 'A', value: 'Restart the database' }, { label: 'B', value: 'Check slow query log and EXPLAIN plans' }, { label: 'C', value: 'Add more indexes immediately' }, { label: 'D', value: 'Increase server RAM' }],
    'B', 'Slow query log identifies problematic queries. EXPLAIN shows execution plan.', 'HARD', 'Scenario', 3),
  mcq('fp-s5', 'Why should we hire you?',
    [{ label: 'A', value: 'I need a job' }, { label: 'B', value: 'My skills align with your requirements and I can add immediate value' }, { label: 'C', value: 'I am the best candidate' }, { label: 'D', value: 'I will work hard' }],
    'B', 'Focus on alignment between skills and company needs with specific examples.', 'MEDIUM', 'HR Scenario', 2),
  mcq('fp-s6', 'Where do you see yourself in 5 years?',
    [{ label: 'A', value: 'In your chair' }, { label: 'B', value: 'Growing technically and leading impactful projects' }, { label: 'C', value: 'At a different company' }, { label: 'D', value: 'Retired' }],
    'B', 'Show ambition aligned with company growth path.', 'EASY', 'HR Scenario', 1),
  mcq('fp-s7', 'Describe a challenging project you worked on.',
    [{ label: 'A', value: 'I have not had any challenges' }, { label: 'B', value: 'Use STAR: specific challenge, actions taken, measurable result' }, { label: 'C', value: 'Blame team members' }, { label: 'D', value: 'Talk about salary' }],
    'B', 'STAR method with specific metrics and positive outcome.', 'MEDIUM', 'HR Scenario', 2),
  mcq('fp-s8', 'What are your strengths?',
    [{ label: 'A', value: 'I am perfect' }, { label: 'B', value: '2-3 relevant strengths with specific examples' }, { label: 'C', value: 'I have no weaknesses' }, { label: 'D', value: 'I work hard' }],
    'B', 'Relevant strengths backed by evidence from experience.', 'EASY', 'HR Scenario', 1),
  mcq('fp-s9', 'Your biggest weakness?',
    [{ label: 'A', value: 'I work too hard' }, { label: 'B', value: 'Genuine weakness with active improvement steps' }, { label: 'C', value: 'I have no weaknesses' }, { label: 'D', value: 'I am always late' }],
    'B', 'Show self-awareness and active improvement. Be genuine.', 'MEDIUM', 'HR Scenario', 2),
  mcq('fp-s10', 'Why this company?',
    [{ label: 'A', value: 'Good salary' }, { label: 'B', value: 'Company mission, culture, and growth opportunities align with my goals' }, { label: 'C', value: 'Near my home' }, { label: 'D', value: 'No particular reason' }],
    'B', 'Research company values, products, culture. Show genuine interest.', 'EASY', 'HR Scenario', 1),
  mcq('fp-s11', 'How do you handle pressure?',
    [{ label: 'A', value: 'I cannot handle pressure' }, { label: 'B', value: 'Prioritize tasks, communicate proactively, and focus on solutions' }, { label: 'C', value: 'I ignore it' }, { label: 'D', value: 'I complain' }],
    'B', 'Show structured approach: prioritize, communicate, execute.', 'MEDIUM', 'HR Scenario', 2),
  mcq('fp-s12', 'Questions for us?',
    [{ label: 'A', value: 'No questions' }, { label: 'B', value: 'Ask about team structure, growth path, and current challenges' }, { label: 'C', value: 'Ask about salary only' }, { label: 'D', value: 'Ask about holidays' }],
    'B', 'Thoughtful questions show genuine interest and research.', 'EASY', 'HR Scenario', 1),
  // Additional coding from pool
  coding('fp-c1', 'Two Sum', 'Given array and target, return indices of two numbers.', '2 ≤ nums.length ≤ 10⁴', 'nums=[2,7,11,15],target=9', '[0,1]',
    [{ input: '[2,7,11,15],9', expectedOutput: '[0,1]' }], [], STARTER, 'EASY', 'Arrays', 3),
  coding('fp-c2', 'Reverse Linked List', 'Reverse singly linked list.', '0 ≤ nodes ≤ 5000', '[1,2,3,4,5]', '[5,4,3,2,1]',
    [{ input: '[1,2,3,4,5]', expectedOutput: '[5,4,3,2,1]' }], [], STARTER, 'EASY', 'Linked Lists', 3),
  coding('fp-c3', 'Valid Parentheses', 'Check if brackets string is valid.', '1 ≤ s.length ≤ 10⁴', '"()[]{}"', 'true',
    [{ input: '"()"', expectedOutput: 'true' }, { input: '"(]"', expectedOutput: 'false' }], [], STARTER, 'EASY', 'Stacks', 3),
  coding('fp-c4', 'Maximum Subarray', 'Find contiguous subarray with largest sum.', '1 ≤ nums.length ≤ 10⁵', '[-2,1,-3,4,-1,2,1,-5,4]', '6',
    [{ input: '[-2,1,-3,4,-1,2,1,-5,4]', expectedOutput: '6' }], [], STARTER, 'MEDIUM', 'Arrays', 4),
  coding('fp-c5', 'Coin Change', 'Min coins to make amount.', '1 ≤ coins.length ≤ 12', '[1,2,5],11', '3',
    [{ input: '[1,2,5],11', expectedOutput: '3' }], [], STARTER, 'MEDIUM', 'DP', 4),
]

// ═══════════════════════════════════════════════════════════════
// ASSESSMENT DEFINITIONS
// ═══════════════════════════════════════════════════════════════
export const MOCK_ASSESSMENTS: MockAssessment[] = [
  {
    id: 'aptitude-assessment',
    title: 'Aptitude Assessment',
    description: 'Comprehensive aptitude test covering quantitative, logical reasoning, verbal ability, and data interpretation. Pattern based on TCS, Infosys, Wipro, Accenture placement exams.',
    type: 'APTITUDE',
    duration: 45,
    totalQuestions: 40,
    totalMarks: 55,
    passingMarks: 22,
    negativeMarking: 0.25,
    questions: APTITUDE_POOL,
    questionPoolSize: APTITUDE_POOL.length,
    randomizeOnRetake: true,
  },
  {
    id: 'dsa-assessment',
    title: 'DSA Assessment',
    description: 'Data Structures & Algorithms assessment with MCQs and coding problems. Covers arrays, linked lists, trees, graphs, DP, sorting, searching. Includes compiler-evaluated coding.',
    type: 'DSA',
    duration: 60,
    totalQuestions: 40,
    totalMarks: 85,
    passingMarks: 34,
    negativeMarking: 0.25,
    questions: DSA_POOL,
    questionPoolSize: DSA_POOL.length,
    randomizeOnRetake: true,
  },
  {
    id: 'core-cs-assessment',
    title: 'Core CS Assessment',
    description: 'Core Computer Science covering Operating Systems, DBMS, Computer Networks, OOPs, and SQL. Practical SQL query writing included.',
    type: 'CORE_CS',
    duration: 45,
    totalQuestions: 40,
    totalMarks: 60,
    passingMarks: 24,
    negativeMarking: 0.25,
    questions: CORE_CS_POOL,
    questionPoolSize: CORE_CS_POOL.length,
    randomizeOnRetake: true,
  },
  {
    id: 'company-specific-assessment',
    title: 'Company-Specific Assessment',
    description: 'Mixed assessment with questions from TCS, Infosys, Wipro, Accenture, Cognizant, Deloitte, Capgemini, Virtusa, Amazon, Google, Microsoft, Uber patterns.',
    type: 'COMPANY_SPECIFIC',
    duration: 60,
    totalQuestions: 40,
    totalMarks: 80,
    passingMarks: 32,
    negativeMarking: 0.25,
    questions: COMPANY_SPECIFIC_POOL,
    questionPoolSize: COMPANY_SPECIFIC_POOL.length,
    randomizeOnRetake: true,
    companyPattern: 'multi-company',
  },
  {
    id: 'full-placement-assessment',
    title: 'Full Placement Test',
    description: 'Complete placement simulation: aptitude, DSA, core CS, company-specific, scenario-based HR, and coding. Mirrors actual campus placement drive.',
    type: 'FULL_PLACEMENT',
    duration: 90,
    totalQuestions: 40,
    totalMarks: 90,
    passingMarks: 36,
    negativeMarking: 0.25,
    questions: FULL_PLACEMENT_POOL,
    questionPoolSize: FULL_PLACEMENT_POOL.length,
    randomizeOnRetake: true,
  },
]

// ═══════════════════════════════════════════════════════════════
// RANDOMIZATION & HELPER FUNCTIONS
// ═══════════════════════════════════════════════════════════════

function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array]
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }
  return shuffled
}

function balanceDifficulty(questions: MockQuestion[], count: number): MockQuestion[] {
  const easy = questions.filter(q => q.difficulty === 'EASY')
  const medium = questions.filter(q => q.difficulty === 'MEDIUM')
  const hard = questions.filter(q => q.difficulty === 'HARD')

  const easyCount = Math.floor(count * 0.4)
  const mediumCount = Math.floor(count * 0.4)
  const hardCount = count - easyCount - mediumCount

  const selected = [
    ...shuffleArray(easy).slice(0, easyCount),
    ...shuffleArray(medium).slice(0, mediumCount),
    ...shuffleArray(hard).slice(0, hardCount),
  ]

  return shuffleArray(selected).map((q, i) => ({ ...q, orderIndex: i }))
}

export function getRandomizedAssessment(
  assessmentId: string,
  previousAttemptQuestionIds?: string[]
): MockAssessment | null {
  const assessment = MOCK_ASSESSMENTS.find(a => a.id === assessmentId)
  if (!assessment) return null

  if (!assessment.randomizeOnRetake) return assessment

  let pool = [...assessment.questions]

  if (previousAttemptQuestionIds && previousAttemptQuestionIds.length > 0) {
    const unseen = pool.filter(q => !previousAttemptQuestionIds.includes(q.id))
    if (unseen.length >= assessment.totalQuestions) {
      pool = unseen
    }
  }

  const balanced = balanceDifficulty(pool, assessment.totalQuestions)
  const totalMarks = balanced.reduce((sum, q) => sum + q.marks, 0)

  return {
    ...assessment,
    questions: balanced,
    totalMarks,
    passingMarks: Math.ceil(totalMarks * 0.4),
  }
}

export function getAssessmentById(id: string): MockAssessment | undefined {
  return MOCK_ASSESSMENTS.find(a => a.id === id)
}

export function getAllAssessments(): MockAssessment[] {
  return MOCK_ASSESSMENTS
}

export function getCompanyTags(): string[] {
  const tags = new Set<string>()
  for (const pool of [APTITUDE_POOL, DSA_POOL, CORE_CS_POOL, COMPANY_SPECIFIC_POOL, FULL_PLACEMENT_POOL]) {
    for (const q of pool) {
      q.companyTags?.forEach(t => tags.add(t))
    }
  }
  return Array.from(tags).sort()
}

export function getQuestionsByCompany(company: string): MockQuestion[] {
  const all = [...APTITUDE_POOL, ...DSA_POOL, ...CORE_CS_POOL, ...COMPANY_SPECIFIC_POOL, ...FULL_PLACEMENT_POOL]
  return all.filter(q => q.companyTags?.includes(company))
}
